version: '3'

tasks:
  example:
    desc: "Run program by regenerating example enums"
    cmds:
      - go run ./cmd/goenums/ ./examples/config/enums.json ./examples/enums/

  test:
    desc: "Run tests"
    cmds:
      - go test ./...

  build:
    desc: "Build program"
    cmds:
      - go build -o ./bin/ ./cmd/goenums/
