package auth

import "fmt"

// This file is generated by goenums; DO NOT EDIT

// AccountStatus wraps an enum value of type accountStatus to enforce type safety.
type AccountStatus struct {
	accountStatus
}

// accountStatus is the underlying type of AccountStatus and should not be used directly.
type accountStatus int

const (
	unknownAccountStatus accountStatus = iota
	activeAccountStatus
	inactiveAccountStatus
	suspendedAccountStatus
)

var (
	strAccountStatusArray = [...]string{
		activeAccountStatus:    "ACTIVE",
		inactiveAccountStatus:  "INACTIVE",
		suspendedAccountStatus: "SUSPENDED",
	}

	typeAccountStatusMap = map[string]accountStatus{
		"ACTIVE":    activeAccountStatus,
		"INACTIVE":  inactiveAccountStatus,
		"SUSPENDED": suspendedAccountStatus,
	}
)

// String returns the string representation of the enum value
func (a accountStatus) String() string {
	return strAccountStatusArray[a]
}

// ParseAccountStatus attempts to parse the given value into AccountStatus.
// It supports string, fmt.Stringer, int, int64, and int32.
// If the value is not a valid AccountStatus or the value is not a supported type, it will return the enums unknown value (unknownAccountStatus).
func ParseAccountStatus(a any) AccountStatus {
	switch v := a.(type) {
	case AccountStatus:
		return v
	case string:
		return AccountStatus{stringToAccountStatus(v)}
	case fmt.Stringer:
		return AccountStatus{stringToAccountStatus(v.String())}
	case int:
		return AccountStatus{accountStatus(v)}
	case int64:
		return AccountStatus{accountStatus(int(v))}
	case int32:
		return AccountStatus{accountStatus(int(v))}
	}
	return AccountStatus{unknownAccountStatus}
}

// stringToAccountStatus attempts to parse the given string into AccountStatus.
// If the value is not a valid AccountStatus, it will return the enums unknown value (unknownAccountStatus).
func stringToAccountStatus(s string) accountStatus {
	if v, ok := typeAccountStatusMap[s]; ok {
		return v
	}
	return unknownAccountStatus
}

// IsValid returns true if the enum value is valid.
// The unknown value (unknownAccountStatus) is not considered valid.
func (a accountStatus) IsValid() bool {
	return a >= accountStatus(1) && a <= accountStatus(len(strAccountStatusArray))
}

// AccountStatusContainer contains all possible values of type AccountStatus.
type AccountStatusContainer struct {
	UNKNOWN   AccountStatus
	ACTIVE    AccountStatus
	INACTIVE  AccountStatus
	SUSPENDED AccountStatus
}

// AccountStatuses is a global instance of AccountStatusContainer that contains all possible values of type AccountStatus.
var AccountStatuses = AccountStatusContainer{
	UNKNOWN:   AccountStatus{unknownAccountStatus},
	ACTIVE:    AccountStatus{activeAccountStatus},
	INACTIVE:  AccountStatus{inactiveAccountStatus},
	SUSPENDED: AccountStatus{suspendedAccountStatus},
}

// All returns a slice containing all possible values of type AccountStatus.
func (c AccountStatusContainer) All() []AccountStatus {
	return []AccountStatus{
		c.ACTIVE,
		c.INACTIVE,
		c.SUSPENDED,
	}
}

// MarshalJSON returns the JSON representation of the enum value.
func (a *AccountStatus) MarshalJSON() ([]byte, error) {
	return []byte(`"` + a.String() + `"`), nil
}

// UnmarshalJSON parses the JSON representation of the enum value.
func (a *AccountStatus) UnmarshalJSON(b []byte) error {
	*a = ParseAccountStatus(string(b))
	return nil
}
