output_path: ./examples/enums
enums:
  - package: auth
    type: Role
    values:
      - Admin
      - User
      - Guest
  - package: auth
    type: Status
    values:
      - Active
      - Inactive
      - Suspended
