name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        include:
          - goos: windows
            goarch: 386
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o goenums_${{ matrix.goos }}_${{ matrix.goarch }} .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: goenums_${{ matrix.goos }}_${{ matrix.goarch }}
          path: goenums_${{ matrix.goos }}_${{ matrix.goarch }}
